export const STATES_ALLOWING_THERAPY_AND_INSURANCE = ["TX", "FL", "NY", "NC", "IL", "MA", "TN"]
export const STATES_DISALLOWING_ASSESSMENT = ["AK", "CA", "HI", "IA", "LA", "MS", "MT", "NM", "OR", "SD"]
export const ACCEPTED_INSURANCES = ['Aetna', 'BCBS']
export const UNINSURED_ASSESSMENT_COST_IN_DOLLARS = 950
export const UNINSURED_THERAPY_COST_IN_DOLLARS = 125